openapi: 3.0.0  
info:
  title: LOLTracker API
  description: Simple API for user login and player performance
  contact:
    email: pchen109@bcit.ca
  version: '1'
paths:
  /lol/login:
    get:
      summary: Retrieve user login information
      operationId: app.get_user_login_info
      description: This endpoint fetches the user's login information, including their username and login streak
      parameters:
        - name: index
          in: query
          description: index of the user login report
          required: true
          schema:
            type: integer
            example: 100
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "404":
          description: not Found

  /lol/performance:
    get:
      summary: Retrieve user player performance information
      operationId: app.get_player_performance
      description: This endpoint fetches the playeys state, including KDA and game length
      parameters:
        - name: index
          in: query
          description: index of the player performance report
          required: true
          schema:
            type: integer
            example: 100
      responses:
        "201":
          description: item created
        "400":
          description: "invalid input, object invalid"
        "404":
          description: not Found

  /stats:
    get:
      summary: Retrieves login and performance report stats
      operationId: app.get_stats
      description: Returns login activity and performance metrics, including user trends and KDA stats.
      responses:
        '200':
          description: Successfully retrieved login and performance statistics.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Bad request. Invalid input parameters.

  /login_ids:
    get:
      summary: returns list of login's event ids and trace ids
      operationId: app.get_login_ids
      description: get login's event ids and trace ids
      responses:
        "200":
          description: Successfully returned the list of login's event ids and trace ids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginIds'

  /performance_ids:
    get:
      summary: returns list of performance's event ids and trace ids
      operationId: app.get_performacne_ids
      description: get performance's event ids and trace ids
      responses:
        "200":
          description: Successfully returned the list of performance's event ids and trace ids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerformanceIds'


components:
  schemas:
    ReadingStats:
      required:
        - login_counts
        - performance_counts
      properties:
        login_counts:
          type: integer
          example: 500000
        performance_counts:
          type: integer
          example: 500000
      type: object

    LoginIds:
      required:
        - event_id
        - trace_id
        - event_type
      properties:
        event_id:
          type: string
          example: PTgWU#YGdxY
        trace_id:
          type: string
          example: 570b25da-a76e-4a30-9e2a-1e2cd780d7ac
        event_type:
          type: string
          example: login
      type: object

    PerformanceIds:
      required:
        - event_id
        - trace_id
      properties:
        event_id:
          type: string
          example: af06738a-d19a-4cf3-bb0a-fa450531f556
        trace_id:
          type: string
          example: bf741edd-ba26-4411-b17e-3b4c6f7df6f8
        event_type:
          type: string 
          example: performance
      type: object