version: 1
events:
  hostname: kafka
  port: 9092
  topic: events
datastore:
  filename: stats.json
schema:
  stat: {
            "num_logins": 0,
            "num_performance_report": 0,
        }