openapi: 3.0.0  
info:
  title: LOLTracker API
  description: Simple API for user login and player performance
  contact:
    email: pchen109@bcit.ca
  version: '1'
paths:
  /lol/login:
    get:
      tags:
        - devices
      summary: returns user login information
      operationId: app.get_user_login_info
      description: Gets login info added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of logins returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
        - name: end_timestamp
          in: query
          description: Limits the number of logins returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
      responses:
        "200":
          description: Successfully returned a list of login events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserLogin"

  /lol/performance:
    get:
      tags:
        - devices
      summary: returns user performance information
      operationId: app.get_player_performance
      description: Gets player performance info added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of player performance returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
        - name: end_timestamp
          in: query
          description: Limits the number of player performance returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
      responses:
        "200":
          description: Successfully returned a list of player performance events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerPerformance"

  /records:
    get:
      summary: returns numbers of each record
      operationId: app.get_record_numbers
      description: count number of records
      responses:
        "200":
          description: Successfully returned all record numbers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecordNumbers"

  /login_ids:
    get:
      summary: returns list of login's event ids and trace ids
      operationId: app.get_login_ids
      description: get login's event ids and trace ids
      responses:
        "200":
          description: Successfully returned the list of login's event ids and trace ids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginIds'

  /performance_ids:
    get:
      summary: returns list of performance's event ids and trace ids
      operationId: app.get_performacne_ids
      description: get performance's event ids and trace ids
      responses:
        "200":
          description: Successfully returned the list of performance's event ids and trace ids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerformanceIds'


components:
  schemas:
    UserLogin:
      required:
      - user_id
      - region
      - login_streak
      - timestamp
      - trace_id
      type: object
      properties:
        user_id:
          type: string
          description: users' in-game-name
          format: uuid
          example: zebra-#zoo
        region:
          type: string
          description: server location
          example: Whistler
        login_streak:
          type: integer
          description: number of login in consecutive days
          example: 7
        timestamp:
          type: string
          description: timestamp when login happened
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        trace_id:
          type: string
          description: unique trace ID
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000

    PlayerPerformance:
      required:
      - user_id
      - match_id
      - kills
      - deaths
      - assists
      - timestamp
      - game_length
      - trace_id
      type: object
      properties:
        user_id:
          type: string
          description: users' in-game-name
          format: uuid
          example: zebra-#zoo
        match_id:
          type: string
          description: match ID 
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        kills:
          type: integer
          description: number of kills in one game
          example: 5
        deaths:
          type: integer
          description: number of deaths in one game
          example: 2
        assists:
          type: integer
          description: number of assists in one game
          example: 8
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        game_length:
          type: integer
          description: length of the game in seconds
          example: 1515
        trace_id:
          type: string
          description: unique trace ID
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000

    RecordNumbers:
      required:
        - login_counts
        - performance_counts
      properties:
        login_counts:
          type: integer
          example: 500000
        performance_counts:
          type: integer
          example: 500000
      type: object

    LoginIds:
      required:
        - event_id
        - trace_id
        - event_type
      properties:
        event_id:
          type: string
          example: PTgWU#YGdxY
        trace_id:
          type: string
          example: 570b25da-a76e-4a30-9e2a-1e2cd780d7ac
        event_type:
          type: string
          example: login
      type: object

    PerformanceIds:
      required:
        - event_id
        - trace_id
      properties:
        event_id:
          type: string
          example: af06738a-d19a-4cf3-bb0a-fa450531f556
        trace_id:
          type: string
          example: bf741edd-ba26-4411-b17e-3b4c6f7df6f8
        event_type:
          type: string
          example: performance
      type: object