- name: Deploy Application
  hosts: project_lab_9_Tim
  become: true

  vars:
    ansible_user: ubuntu
    repo_url: "git@github.com:pchen109/Lab-9-redo.git"
    proj_det: "/home/ubuntu/project"

  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Copy SSH key to VM
      ansible.builtin.copy:
        src: /home/garen/.ssh/lab9_redo
        dest: /home/ubuntu/.ssh/lab9_redo
        mode: '0600'

    - name: Clone the repository from GitHub
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ proj_det }}"
        clone: yes   # Clone the repository if it does not exist
        update: yes  # Update the repository if it exists
        key_file: /home/ubuntu/.ssh/lab9_redo
        accept_hostkey: true 
        force: true

    - name: Install required dependencies for Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Create apt keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.shell:
        cmd: |
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: true    # need explicit sudo permissions

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: Install Docker and related components
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Create Docker group if it does not exist
      ansible.builtin.group:
        name: docker
        state: present

    ### Need to relogin to apply group changes
    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: true

    ### CONFIGURATION ######################################################
    - name: Copy conf folder to remote node
      ansible.builtin.copy:
        src: "/mnt/d/OneDrive - BCIT/4.2 - A3855 - Architecture/Lab/Lab-9-redo/conf"
        dest: /home/ubuntu/project/
        owner: nobody 
        group: nogroup 
        mode: "0755" 

    - name: Set permissions on config files
      ansible.builtin.file:
        path: "/home/ubuntu/project/conf/{{ item }}"
        mode: "0644"
      loop:
        - analyzer_config.yml
        - log_config.yml
        - processing_config.yml
        - receiver_config.yml
        - storage_config.yml

    ### Data/Processing/output.json ########################################
    - name: Ensure data and processing directories exist on remote node
      ansible.builtin.file:
        path: /home/ubuntu/project/data/processing
        state: directory
        owner: nobody
        group: nogroup
        mode: "0755"

    - name: Copy output.json file to remote node
      ansible.builtin.copy:
        src: "/mnt/d/OneDrive - BCIT/4.2 - A3855 - Architecture/Lab/Lab-9-redo/data/processing/output.json"
        dest: /home/ubuntu/project/data/processing 
        owner: nobody 
        group: nogroup 
        mode: "0644" 

    ### Logs ################################################################
    - name: Copy logs folder to remote node
      ansible.builtin.copy:
        src: "/mnt/d/OneDrive - BCIT/4.2 - A3855 - Architecture/Lab/Lab-9-redo/logs"
        dest: /home/ubuntu/project/ 
        owner: nobody 
        group: nogroup 
        mode: "0755" 

    - name: Set permissions on log files
      ansible.builtin.file:
        path: "/home/ubuntu/project/logs/{{ item }}"
        mode: "0644"
      loop:
        - analyzer.log
        - processing.log
        - receiver.log
        - storage.log
        - test.log

    ### ENV ################################################################
    - name: Copy env file to remote node
      ansible.builtin.copy:
        src: "/mnt/d/OneDrive - BCIT/4.2 - A3855 - Architecture/Lab/Lab-9-redo/.env"
        dest: /home/ubuntu/project/
        owner: nobody 
        group: nogroup 
        mode: "644" 

    ### Docker Compose ####################################################
    - name: Run Docker Compose to start the services
      ansible.builtin.shell:
        cmd: "docker compose up -d --build"
      args:
        chdir: "{{ proj_det }}"

    - name: Wait for 10 seconds before retrying Docker Compose
      ansible.builtin.pause:
        seconds: 10

    - name: Retry Docker Compose to ensure all services are up
      ansible.builtin.shell:
        cmd: "docker compose up -d"
      args:
        chdir: "{{ proj_det }}"